#!/usr/bin/env bash
#creating a file called /var/run/myscript.pid containg it's pid
function delete() {
    rm /var/run/holbertonscript.pid
    exit
}

trap "echo I hate the kill command;love" SIGTERM
trap "echo Y U no love me?!;love" SIGINT

echo $$ >> /var/run/myscript.pid
while [ true ]; do
    echo To infinity and beyond;
done
