#!/usr/bin/env bash
#this program is desgned to manage the manange_my_process file

start_fn() {
	./manage_my_process > /tmp/my_proicess &
	echo $! > /var/run/my_process.pid
	echo "manage_my_process started"
}

#the stop funtion
stop_fn() {
	if pgrep "manage_my_process" > /dev/null;then
		kill $(cat /var/run/my_process.pid)
	fi
        rm -r /var/run/my_process.pid
	echo "manage_my_process stopped"
}

#the restart funtion
restart_fn() {
	stop_fn
	start_fn
	echo "manage_my_process restarted"
}

input_pt() {
	echo "Usage: manage_my_process {start|stop|restart}"
	
}


case $1 in
	start)
		start_fn
		;;
	stop)
		stop_fn
		;;
	restart)
		restart_fn
		;;
	*)
		if [[ -z $1 ]]; then
			input_pt
		else
			echo "Usage: manage_my_process {start|stop|restart}"
		fi

		;;
esac		
